import { Race, DaySchedule, Horse } from "@/lib/types";

// Helper: default profile data factory
function profile(overrides: {
    aiVerdict: string;
    pros: string[];
    cons: string[];
    confidence: number;
    age: number;
    weight: string;
    rating: number;
    trackRecord: Horse["trackRecord"];
    recentRuns: Horse["recentRuns"];
}) {
    return overrides;
}

export const cheltenhamDay1: Race[] = [
    {
        id: "race-1",
        time: "13:30",
        name: "Supreme Novices' Hurdle",
        grade: "Grade 1",
        distance: "2m 87y",
        going: "Good to Soft",
        runners: 16,
        status: "upcoming",
        bankerPick: "Ballyburn",
        valuePick: "Hunters Yarn",
        marketMover: "Gaelic Warrior",
        punditPick: "Sir Gino",
        topSignals: [
            { type: "BANKER", label: "Banker: Ballyburn" },
            { type: "VALUE_BET", label: "Value: Hunters Yarn" },
            { type: "STEAMING", label: "Steaming: Gaelic Warrior" },
            { type: "PUNDIT_PICK", label: "Pundit: Sir Gino" },
        ],
        horses: [
            {
                id: "h1",
                number: 1,
                name: "Ballyburn",
                jockey: "P. Townend",
                trainer: "W.P. Mullins",
                form: "111-11",
                odds: "6/4",
                oddsDecimal: 2.5,
                aiRating: 92,
                crowdPickPercent: 34,
                signals: [{ type: "BANKER", label: "BANKER" }],
                sentiment: { positive: 82, negative: 8, neutral: 10 },
                stats: { speed: 94, stamina: "High", trend: "up" },
                aiInsight:
                    "Outstanding record and unbeaten over hurdles. W.P. Mullins has an exceptional record in this race. Market confidence is justified — this is the standout.",
                silkColor: "#1a5c2e",
                ...profile({
                    aiVerdict:
                        "Talented horse with an impeccable record over hurdles. Five wins from five starts tells its own story. W.P. Mullins has won this race more than any other trainer and Paul Townend is the perfect jockey for the occasion. The only concern is whether the price fully reflects the quality — at 6/4 there's not a lot of margin, but the probability supports it.",
                    pros: [
                        "Unbeaten over hurdles — five from five",
                        "Top trainer/jockey combination (Mullins/Townend)",
                        "Exceptional Supreme Novices' record for connections",
                        "Strong ground suitability for Good to Soft",
                    ],
                    cons: [
                        "Short price — limited each-way value",
                        "Step up in class from maiden/novice",
                        "Untested against this calibre of opposition",
                    ],
                    confidence: 88,
                    age: 6,
                    weight: "11st 7lb",
                    rating: 156,
                    trackRecord: {
                        courseWins: 1,
                        courseRuns: 1,
                        distanceWins: 3,
                        distanceRuns: 4,
                        goingWins: 4,
                        goingRuns: 5,
                    },
                    recentRuns: [
                        { date: "2026-02-08", course: "Leopardstown", position: "1st", distance: "2m", going: "Yielding", odds: "1/3" },
                        { date: "2026-01-11", course: "Punchestown", position: "1st", distance: "2m 1f", going: "Soft", odds: "2/7" },
                        { date: "2025-12-26", course: "Leopardstown", position: "1st", distance: "2m", going: "Yielding", odds: "4/11" },
                    ],
                }),
            },
            {
                id: "h2",
                number: 2,
                name: "Sir Gino",
                jockey: "H. Cobden",
                trainer: "H. De Bromhead",
                form: "11-121",
                odds: "3/1",
                oddsDecimal: 4.0,
                aiRating: 85,
                crowdPickPercent: 21,
                signals: [{ type: "PUNDIT_PICK", label: "PUNDIT PICK" }],
                sentiment: { positive: 71, negative: 14, neutral: 15 },
                stats: { speed: 91, stamina: "High", trend: "stable" },
                aiInsight:
                    "Strong credentials but faces a tough ask against the favourite. ITV Racing have him as their nap — trainer in good form with festival runners.",
                silkColor: "#2c1a5c",
                ...profile({
                    aiVerdict:
                        "A strong contender backed by pundit consensus. ITV Racing's nap selection for the day. Good form figures and a trainer who knows how to target Cheltenham. However, the head-to-head with Ballyburn looks daunting on paper. Best chance at the price is if the favourite underperforms.",
                    pros: [
                        "ITV Racing nap — strong pundit backing",
                        "Trainer targeting Cheltenham specifically",
                        "Proven at Grade 1 level already",
                    ],
                    cons: [
                        "Faces a seemingly superior Ballyburn",
                        "Slight stamina doubt at this trip",
                        "Recent form not as strong as peak",
                    ],
                    confidence: 72,
                    age: 6,
                    weight: "11st 7lb",
                    rating: 150,
                    trackRecord: {
                        courseWins: 0,
                        courseRuns: 1,
                        distanceWins: 3,
                        distanceRuns: 5,
                        goingWins: 2,
                        goingRuns: 4,
                    },
                    recentRuns: [
                        { date: "2026-02-01", course: "Sandown", position: "2nd", distance: "2m", going: "Good to Soft", odds: "5/4" },
                        { date: "2026-01-01", course: "Kempton", position: "1st", distance: "2m", going: "Good", odds: "8/13" },
                        { date: "2025-11-23", course: "Ascot", position: "1st", distance: "2m 1f", going: "Soft", odds: "11/8" },
                    ],
                }),
            },
            {
                id: "h3",
                number: 3,
                name: "Hunters Yarn",
                jockey: "J.W. Kennedy",
                trainer: "G. Elliott",
                form: "21-211",
                odds: "14/1",
                oddsDecimal: 15.0,
                aiRating: 73,
                crowdPickPercent: 8,
                signals: [{ type: "VALUE_BET", label: "VALUE BET" }],
                sentiment: { positive: 55, negative: 20, neutral: 25 },
                stats: { speed: 82, stamina: "Elite", trend: "up" },
                aiInsight:
                    "Market is underestimating this one. Strong festival form for Gordon Elliott and the stamina profile suits this test. Value at the current price.",
                silkColor: "#5c3a1a",
                ...profile({
                    aiVerdict:
                        "A genuine value bet at 14/1. Our model prices this horse closer to 7/1, giving significant edge. Gordon Elliott has an incredible Cheltenham Festival record and targets his horses specifically. The stamina profile is elite, which is crucial in a race that often falls apart from the front. The market is sleeping on this one.",
                    pros: [
                        "Massive value — model says 7/1 fair price",
                        "Elite stamina for a race that tests fitness",
                        "Gordon Elliott's festival-targeting approach",
                        "Improving form trajectory",
                    ],
                    cons: [
                        "Untested at Grade 1 level",
                        "Jockey booking less fashionable",
                        "Needs to step up significantly on ratings",
                    ],
                    confidence: 68,
                    age: 7,
                    weight: "11st 7lb",
                    rating: 142,
                    trackRecord: {
                        courseWins: 0,
                        courseRuns: 2,
                        distanceWins: 2,
                        distanceRuns: 3,
                        goingWins: 3,
                        goingRuns: 5,
                    },
                    recentRuns: [
                        { date: "2026-02-15", course: "Navan", position: "1st", distance: "2m 1f", going: "Soft", odds: "5/2" },
                        { date: "2026-01-04", course: "Fairyhouse", position: "2nd", distance: "2m", going: "Yielding", odds: "7/2" },
                        { date: "2025-12-28", course: "Leopardstown", position: "1st", distance: "2m", going: "Yielding to Soft", odds: "4/1" },
                    ],
                }),
            },
            {
                id: "h4",
                number: 4,
                name: "Gaelic Warrior",
                jockey: "D.N. Russell",
                trainer: "W.P. Mullins",
                form: "1-1121",
                odds: "5/1",
                oddsDecimal: 6.0,
                aiRating: 80,
                crowdPickPercent: 17,
                signals: [{ type: "STEAMING", label: "STEAMING" }],
                sentiment: { positive: 68, negative: 12, neutral: 20 },
                stats: { speed: 88, stamina: "High", trend: "up" },
                aiInsight:
                    "Significant market support in the last 24 hours. Odds have shortened from 10/1 to 5/1 — smart money is flowing. Second string from the Mullins yard.",
                silkColor: "#1a3a5c",
                ...profile({
                    aiVerdict:
                        "Significant market mover. Odds have shortened from 10/1 to 5/1 in the final 24 hours — this is the clearest sign of smart money in the race. As Mullins' second string, there may be private information driving confidence. Worth respecting the move.",
                    pros: [
                        "Massive market support — 10/1 to 5/1",
                        "Second string from dominant Mullins yard",
                        "Davy Russell booking adds experience",
                        "Good form at competitive level",
                    ],
                    cons: [
                        "Stable second choice behind Ballyburn",
                        "Market move may reflect insider knowledge — or hype",
                        "Price has shortened beyond fair value",
                    ],
                    confidence: 74,
                    age: 6,
                    weight: "11st 7lb",
                    rating: 148,
                    trackRecord: {
                        courseWins: 0,
                        courseRuns: 0,
                        distanceWins: 3,
                        distanceRuns: 4,
                        goingWins: 2,
                        goingRuns: 3,
                    },
                    recentRuns: [
                        { date: "2026-02-11", course: "Leopardstown", position: "1st", distance: "2m", going: "Yielding", odds: "6/4" },
                        { date: "2026-01-15", course: "Naas", position: "2nd", distance: "2m 1f", going: "Soft", odds: "2/1" },
                        { date: "2025-12-26", course: "Leopardstown", position: "1st", distance: "2m", going: "Yielding", odds: "9/4" },
                    ],
                }),
            },
            {
                id: "h5",
                number: 5,
                name: "Doyen Quest",
                jockey: "R. Power",
                trainer: "J.P. O'Brien",
                form: "31-312",
                odds: "20/1",
                oddsDecimal: 21.0,
                aiRating: 58,
                crowdPickPercent: 5,
                signals: [{ type: "DRIFTING", label: "DRIFTING" }],
                sentiment: { positive: 35, negative: 40, neutral: 25 },
                stats: { speed: 75, stamina: "Medium", trend: "down" },
                aiInsight:
                    "Odds have drifted significantly from 12/1 to 20/1. Money moving away from this one. The form doesn't suggest a festival-calibre performance.",
                silkColor: "#5c1a1a",
                ...profile({
                    aiVerdict:
                        "The market is sending a clear negative signal. Drifting from 12/1 to 20/1 in the final days suggests connections may not be confident. The form figures are inconsistent and there's nothing to suggest this horse can compete at the highest level today.",
                    pros: [
                        "Big price — huge return if it clicks",
                        "Experienced jockey in R. Power",
                    ],
                    cons: [
                        "Drifting significantly in the market",
                        "Inconsistent form figures",
                        "Mediocre stamina for this test",
                        "Negative social sentiment prevailing",
                    ],
                    confidence: 32,
                    age: 7,
                    weight: "11st 7lb",
                    rating: 135,
                    trackRecord: {
                        courseWins: 0,
                        courseRuns: 2,
                        distanceWins: 1,
                        distanceRuns: 4,
                        goingWins: 1,
                        goingRuns: 3,
                    },
                    recentRuns: [
                        { date: "2026-02-08", course: "Leopardstown", position: "3rd", distance: "2m", going: "Yielding", odds: "8/1" },
                        { date: "2026-01-04", course: "Fairyhouse", position: "2nd", distance: "2m 1f", going: "Soft", odds: "6/1" },
                        { date: "2025-12-01", course: "Navan", position: "1st", distance: "2m", going: "Heavy", odds: "3/1" },
                    ],
                }),
            },
            {
                id: "h6",
                number: 6,
                name: "Mystical Power",
                jockey: "M.P. Walsh",
                trainer: "W.P. Mullins",
                form: "11-214",
                odds: "8/1",
                oddsDecimal: 9.0,
                aiRating: 70,
                crowdPickPercent: 10,
                signals: [{ type: "SOCIAL_BUZZ", label: "SOCIAL BUZZ" }],
                sentiment: { positive: 62, negative: 18, neutral: 20 },
                stats: { speed: 85, stamina: "High", trend: "stable" },
                aiInsight:
                    "High social media activity but the market isn't convinced. 380+ mentions in the last hour on X. Third string from the Mullins yard — each-way claims.",
                silkColor: "#3a5c1a",
                ...profile({
                    aiVerdict:
                        "Social media is buzzing about this horse but the market hasn't fully reacted. As Mullins' third string, this could be the forgotten one — which is exactly where value lies. Each-way at 8/1 has some appeal if the top two from the yard disappoint.",
                    pros: [
                        "High social media buzz — 380+ mentions",
                        "Mullins yard — always dangerous",
                        "Good each-way proposition at 8/1",
                    ],
                    cons: [
                        "Third string from the stable",
                        "Social hype may not translate to performance",
                        "Recent run (4th) was below expectations",
                    ],
                    confidence: 58,
                    age: 6,
                    weight: "11st 7lb",
                    rating: 144,
                    trackRecord: {
                        courseWins: 1,
                        courseRuns: 2,
                        distanceWins: 2,
                        distanceRuns: 3,
                        goingWins: 3,
                        goingRuns: 4,
                    },
                    recentRuns: [
                        { date: "2026-02-11", course: "Leopardstown", position: "4th", distance: "2m", going: "Yielding", odds: "5/1" },
                        { date: "2026-01-04", course: "Punchestown", position: "1st", distance: "2m 1f", going: "Soft", odds: "7/4" },
                        { date: "2025-12-14", course: "Navan", position: "2nd", distance: "2m", going: "Heavy", odds: "2/1" },
                    ],
                }),
            },
        ],
    },
    {
        id: "race-2",
        time: "14:10",
        name: "Arkle Challenge Trophy",
        grade: "Grade 1",
        distance: "1m 7f 199y",
        going: "Good to Soft",
        runners: 12,
        status: "upcoming",
        bankerPick: "Majborough",
        valuePick: "Ginny's Destiny",
        marketMover: "Gaelic Warrior",
        punditPick: "El Fabiolo",
        topSignals: [
            { type: "BANKER", label: "Banker: Majborough" },
            { type: "VALUE_BET", label: "Value: Ginny's Destiny" },
            { type: "STEAMING", label: "Market Mover: Gaelic Warrior" },
            { type: "PUNDIT_PICK", label: "Pundit: El Fabiolo" },
        ],
        horses: [
            {
                id: "h7",
                number: 1,
                name: "Majborough",
                jockey: "P. Townend",
                trainer: "W.P. Mullins",
                form: "11-111",
                odds: "Evs",
                oddsDecimal: 2.0,
                aiRating: 95,
                crowdPickPercent: 41,
                signals: [{ type: "BANKER", label: "BANKER" }],
                sentiment: { positive: 88, negative: 5, neutral: 7 },
                stats: { speed: 98, stamina: "High", trend: "up" },
                aiInsight:
                    "Market noise suggests this horse has been specifically targeted for today. Unbeaten at this distance when carrying < 11st 10lb. Massive value at current odds.",
                silkColor: "#1a5c2e",
                ...profile({
                    aiVerdict:
                        "The standout horse in this race by a distance. Unbeaten in five starts over fences, winning each with increasing authority. W.P. Mullins has targeted the Arkle specifically and Paul Townend gives this horse every chance. At even money, the market is right — this is the banker of the day.",
                    pros: [
                        "Unbeaten over fences — five from five",
                        "Progressive profile — winning distances increasing",
                        "Mullins/Townend combination at Cheltenham",
                        "Specifically targeted for this race",
                    ],
                    cons: [
                        "Even money leaves no margin for error",
                        "Has to handle the Cheltenham atmosphere",
                        "Quality opposition in a Grade 1",
                    ],
                    confidence: 91,
                    age: 6,
                    weight: "11st 7lb",
                    rating: 162,
                    trackRecord: { courseWins: 0, courseRuns: 0, distanceWins: 4, distanceRuns: 5, goingWins: 3, goingRuns: 4 },
                    recentRuns: [
                        { date: "2026-02-08", course: "Leopardstown", position: "1st", distance: "2m", going: "Yielding", odds: "1/4" },
                        { date: "2026-01-11", course: "Punchestown", position: "1st", distance: "2m", going: "Soft", odds: "1/3" },
                        { date: "2025-12-26", course: "Leopardstown", position: "1st", distance: "2m", going: "Yielding", odds: "2/5" },
                    ],
                }),
            },
            {
                id: "h8",
                number: 2,
                name: "El Fabiolo",
                jockey: "P. Townend",
                trainer: "W.P. Mullins",
                form: "11-113",
                odds: "5/2",
                oddsDecimal: 3.5,
                aiRating: 82,
                crowdPickPercent: 24,
                signals: [
                    { type: "PUNDIT_PICK", label: "PUNDIT PICK" },
                    { type: "OVERHYPED", label: "OVERHYPED" },
                ],
                sentiment: { positive: 65, negative: 22, neutral: 13 },
                stats: { speed: 90, stamina: "Medium", trend: "down" },
                aiInsight:
                    "Pundit favourite but the AI sees risk. Last run was below par and the price has shortened on reputation rather than recent evidence. Potential to disappoint.",
                silkColor: "#2c1a5c",
                ...profile({
                    aiVerdict:
                        "A horse trading on reputation from last season. The pundits love this horse but the data tells a different story. That 3rd place last time out is a concern — no horse has won the Arkle coming off a defeat in a decade. The price is too short for the risk profile.",
                    pros: [
                        "Strong pundit consensus — Racing Post nap",
                        "Class is permanent — Grade 1 winner",
                        "Mullins yard aiming at Cheltenham",
                    ],
                    cons: [
                        "Last run (3rd) is a red flag",
                        "Price shortened on name, not form",
                        "Stamina profile only medium — not ideal",
                        "Our model says 4/1 is fair — 5/2 overbet",
                    ],
                    confidence: 55,
                    age: 7,
                    weight: "11st 7lb",
                    rating: 158,
                    trackRecord: { courseWins: 1, courseRuns: 2, distanceWins: 3, distanceRuns: 5, goingWins: 2, goingRuns: 4 },
                    recentRuns: [
                        { date: "2026-02-01", course: "Leopardstown", position: "3rd", distance: "2m", going: "Yielding", odds: "4/7" },
                        { date: "2025-12-28", course: "Leopardstown", position: "1st", distance: "2m", going: "Yielding to Soft", odds: "1/2" },
                        { date: "2025-11-17", course: "Punchestown", position: "1st", distance: "2m", going: "Soft", odds: "4/9" },
                    ],
                }),
            },
            {
                id: "h9",
                number: 3,
                name: "Ginny's Destiny",
                jockey: "J.J. Slevin",
                trainer: "G. Elliott",
                form: "12-111",
                odds: "14/1",
                oddsDecimal: 15.0,
                aiRating: 74,
                crowdPickPercent: 7,
                signals: [{ type: "VALUE_BET", label: "VALUE BET" }],
                sentiment: { positive: 52, negative: 23, neutral: 25 },
                stats: { speed: 84, stamina: "High", trend: "up" },
                aiInsight:
                    "Strong Cheltenham form and trainer in good festival shape. Market likely underestimating this horse. Our model gives a fair price of 7/1 — significant value at 14s.",
                silkColor: "#5c3a1a",
                ...profile({
                    aiVerdict:
                        "The classic \"overlooked\" Cheltenham runner. Gordon Elliott is a a master at placing horses in big-field handicaps and targeting festival glory. At 14/1, our model gives a fair value of 7/1 — that's a significant edge that the market hasn't priced in. The improving form and stamina profile make this a stand-out value play.",
                    pros: [
                        "Enormous value — 14/1 vs 7/1 model price",
                        "Gordon Elliott festival track record",
                        "Improving form curve — three wins on the bounce",
                        "Stamina is high — suits the Cheltenham hill",
                    ],
                    cons: [
                        "Needs to step up in class",
                        "Jockey less proven at the top level",
                        "Ground preference untested at Cheltenham",
                    ],
                    confidence: 70,
                    age: 7,
                    weight: "11st 7lb",
                    rating: 145,
                    trackRecord: { courseWins: 0, courseRuns: 1, distanceWins: 3, distanceRuns: 4, goingWins: 2, goingRuns: 3 },
                    recentRuns: [
                        { date: "2026-02-15", course: "Navan", position: "1st", distance: "2m", going: "Soft", odds: "3/1" },
                        { date: "2026-01-04", course: "Fairyhouse", position: "1st", distance: "2m", going: "Yielding", odds: "5/2" },
                        { date: "2025-12-11", course: "Punchestown", position: "1st", distance: "2m 1f", going: "Heavy", odds: "7/2" },
                    ],
                }),
            },
            {
                id: "h10",
                number: 4,
                name: "Fastorslow",
                jockey: "J.J. Slevin",
                trainer: "M.F. Morris",
                form: "22-112",
                odds: "5/1",
                oddsDecimal: 6.0,
                aiRating: 78,
                crowdPickPercent: 14,
                signals: [{ type: "SOCIAL_BUZZ", label: "SOCIAL BUZZ" }],
                sentiment: { positive: 70, negative: 15, neutral: 15 },
                stats: { speed: 86, stamina: "High", trend: "stable" },
                aiInsight:
                    "Solid each-way contender with good ground suitability. Social media mentions are growing. Track record at Cheltenham is decent.",
                silkColor: "#1a3a5c",
                ...profile({
                    aiVerdict:
                        "A solid, reliable performer that rarely runs a bad race. Social media is starting to notice this horse — mentions up 200% in the last 24 hours. At 5/1 there's reasonable each-way value. Not the most exciting horse but one of the safest each-way bets on the card.",
                    pros: [
                        "Consistent form — rarely out of the top 2",
                        "Growing social media buzz",
                        "Good ground suitability",
                        "Solid each-way proposition",
                    ],
                    cons: [
                        "Lacks a killer turn of foot",
                        "Two second places suggest may not win",
                        "Price reflects the market's view accurately",
                    ],
                    confidence: 66,
                    age: 8,
                    weight: "11st 7lb",
                    rating: 149,
                    trackRecord: { courseWins: 0, courseRuns: 1, distanceWins: 2, distanceRuns: 4, goingWins: 3, goingRuns: 5 },
                    recentRuns: [
                        { date: "2026-02-08", course: "Leopardstown", position: "2nd", distance: "2m", going: "Yielding", odds: "3/1" },
                        { date: "2026-01-11", course: "Naas", position: "1st", distance: "2m", going: "Soft", odds: "7/4" },
                        { date: "2025-12-26", course: "Leopardstown", position: "1st", distance: "2m", going: "Yielding", odds: "5/2" },
                    ],
                }),
            },
            {
                id: "h11",
                number: 5,
                name: "Galopin Des Champs",
                jockey: "P. Townend",
                trainer: "W.P. Mullins",
                form: "11-311",
                odds: "Evs",
                oddsDecimal: 2.0,
                aiRating: 93,
                crowdPickPercent: 38,
                signals: [{ type: "BANKER", label: "BANKER" }],
                sentiment: { positive: 85, negative: 7, neutral: 8 },
                stats: { speed: 96, stamina: "Elite", trend: "up" },
                aiInsight:
                    "Festival specialist with an incredible Cheltenham record. The stats suggest a career-best performance is incoming.",
                silkColor: "#2e5c1a",
                ...profile({
                    aiVerdict:
                        "The king of Cheltenham. Three visits, three wins — including two Gold Cups. Every metric points to a successful defence. The only question is whether age and a heavy campaign have taken their toll, but all the evidence says no.",
                    pros: [
                        "Three wins from three Cheltenham visits",
                        "Peak trainer/jockey combination",
                        "Elite stamina for the Gold Cup test",
                        "Career form suggests another top performance",
                    ],
                    cons: [
                        "Even money is a short price for a championship race",
                        "One blip (3rd at Leopardstown) raises a small flag",
                        "Heavy campaign this season",
                    ],
                    confidence: 90,
                    age: 9,
                    weight: "11st 10lb",
                    rating: 172,
                    trackRecord: { courseWins: 3, courseRuns: 3, distanceWins: 4, distanceRuns: 5, goingWins: 5, goingRuns: 6 },
                    recentRuns: [
                        { date: "2026-02-08", course: "Leopardstown", position: "1st", distance: "3m", going: "Yielding", odds: "4/6" },
                        { date: "2025-12-28", course: "Leopardstown", position: "3rd", distance: "3m", going: "Yielding to Soft", odds: "1/2" },
                        { date: "2025-11-17", course: "Punchestown", position: "1st", distance: "3m", going: "Soft", odds: "4/7" },
                    ],
                }),
            },
        ],
    },
    {
        id: "race-3",
        time: "14:50",
        name: "Ultima Handicap Chase",
        grade: "Grade 3",
        distance: "3m 1f",
        going: "Good to Soft",
        runners: 24,
        status: "upcoming",
        bankerPick: "Corbetts Cross",
        valuePick: "Stage Star",
        punditPick: "Corbetts Cross",
        topSignals: [
            { type: "BANKER", label: "Banker: Corbetts Cross" },
            { type: "VALUE_BET", label: "Value: Stage Star" },
            { type: "SOCIAL_BUZZ", label: "Social Buzz: 580+ mentions" },
        ],
        horses: [
            {
                id: "h12",
                number: 1,
                name: "Corbetts Cross",
                jockey: "J.W. Kennedy",
                trainer: "G. Elliott",
                form: "11-112",
                odds: "7/2",
                oddsDecimal: 4.5,
                aiRating: 88,
                crowdPickPercent: 28,
                signals: [
                    { type: "BANKER", label: "BANKER" },
                    { type: "PUNDIT_PICK", label: "PUNDIT PICK" },
                ],
                sentiment: { positive: 79, negative: 10, neutral: 11 },
                stats: { speed: 87, stamina: "Elite", trend: "up" },
                aiInsight:
                    "Dual pundit and model pick. Ticks every box for this race — stamina, ground, class. Gordon Elliott is having a monster festival.",
                silkColor: "#5c2e1a",
                ...profile({
                    aiVerdict:
                        "A rare dual signal — both the AI model and the pundit consensus agree. This is the horse to beat. Elite stamina, improving form, and a trainer who is absolutely flying at this festival. The 7/2 price looks fair based on the statistical model.",
                    pros: [
                        "Both AI model and pundits agree",
                        "Elite stamina for a gruelling 3m test",
                        "Gordon Elliott in incredible festival form",
                        "Improving form trajectory — getting better with each run",
                    ],
                    cons: [
                        "Big-field handicap — anything can happen",
                        "2nd last time out is a slight concern",
                        "Handicap mark may be catching up",
                    ],
                    confidence: 82,
                    age: 8,
                    weight: "11st 5lb",
                    rating: 155,
                    trackRecord: { courseWins: 1, courseRuns: 2, distanceWins: 3, distanceRuns: 4, goingWins: 4, goingRuns: 5 },
                    recentRuns: [
                        { date: "2026-02-15", course: "Navan", position: "2nd", distance: "3m", going: "Soft", odds: "5/4" },
                        { date: "2026-01-04", course: "Leopardstown", position: "1st", distance: "3m 1f", going: "Yielding", odds: "6/4" },
                        { date: "2025-12-01", course: "Fairyhouse", position: "1st", distance: "3m", going: "Heavy", odds: "2/1" },
                    ],
                }),
            },
            {
                id: "h13",
                number: 2,
                name: "Stage Star",
                jockey: "H. Cobden",
                trainer: "P. Nicholls",
                form: "21-312",
                odds: "12/1",
                oddsDecimal: 13.0,
                aiRating: 71,
                crowdPickPercent: 9,
                signals: [{ type: "VALUE_BET", label: "VALUE BET" }],
                sentiment: { positive: 48, negative: 28, neutral: 24 },
                stats: { speed: 80, stamina: "High", trend: "stable" },
                aiInsight:
                    "Market overlooks the Paul Nicholls factor. Historically his horses peak for Cheltenham. Fair odds around 7/1.",
                silkColor: "#1a5c5c",
                ...profile({
                    aiVerdict:
                        "Paul Nicholls is a master at producing horses to peak at Cheltenham and this one fits the profile perfectly. At 12/1, our model suggests a fair price closer to 7/1. The inconsistent form puts some off, but the class is there.",
                    pros: [
                        "Value — 12/1 vs 7/1 model price",
                        "Paul Nicholls' Cheltenham peak factor",
                        "Class horse on his day",
                    ],
                    cons: [
                        "Inconsistent form figures",
                        "Not won since December",
                        "Ground preference uncertain",
                    ],
                    confidence: 62,
                    age: 8,
                    weight: "11st 2lb",
                    rating: 150,
                    trackRecord: { courseWins: 1, courseRuns: 3, distanceWins: 2, distanceRuns: 4, goingWins: 2, goingRuns: 4 },
                    recentRuns: [
                        { date: "2026-02-01", course: "Sandown", position: "2nd", distance: "3m", going: "Good to Soft", odds: "7/2" },
                        { date: "2026-01-01", course: "Kempton", position: "3rd", distance: "3m", going: "Good", odds: "5/2" },
                        { date: "2025-12-14", course: "Cheltenham", position: "1st", distance: "3m 1f", going: "Soft", odds: "4/1" },
                    ],
                }),
            },
            {
                id: "h14",
                number: 3,
                name: "Gerri Colombe",
                jockey: "J.W. Kennedy",
                trainer: "G. Elliott",
                form: "11-121",
                odds: "9/1",
                oddsDecimal: 10.0,
                aiRating: 75,
                crowdPickPercent: 12,
                signals: [{ type: "SOCIAL_BUZZ", label: "SOCIAL BUZZ", detail: "580+ mentions" }],
                sentiment: { positive: 60, negative: 18, neutral: 22 },
                stats: { speed: 83, stamina: "High", trend: "up" },
                aiInsight:
                    "Trending heavily on social media. Still interesting at 9/1 as an each-way proposition.",
                silkColor: "#3a1a5c",
                ...profile({
                    aiVerdict:
                        "Social media favourite with 580+ mentions in the last hour. The buzz is translating into market movement — odds have already shortened from 12/1. At 9/1, there's still each-way value. A lively outsider.",
                    pros: [
                        "Massive social media buzz",
                        "Improving form — won last two",
                        "Gordon Elliott each-way specialist",
                    ],
                    cons: [
                        "Price may have already shortened too much",
                        "Social hype doesn't always translate",
                        "Needs career-best to win this",
                    ],
                    confidence: 60,
                    age: 9,
                    weight: "11st 0lb",
                    rating: 148,
                    trackRecord: { courseWins: 0, courseRuns: 2, distanceWins: 2, distanceRuns: 3, goingWins: 3, goingRuns: 4 },
                    recentRuns: [
                        { date: "2026-02-08", course: "Leopardstown", position: "1st", distance: "3m", going: "Yielding", odds: "4/1" },
                        { date: "2026-01-04", course: "Fairyhouse", position: "2nd", distance: "3m 1f", going: "Yielding to Soft", odds: "5/1" },
                        { date: "2025-12-14", course: "Navan", position: "1st", distance: "3m", going: "Heavy", odds: "3/1" },
                    ],
                }),
            },
            {
                id: "h15",
                number: 4,
                name: "Fury Road",
                jockey: "R. Power",
                trainer: "W.P. Mullins",
                form: "32-213",
                odds: "16/1",
                oddsDecimal: 17.0,
                aiRating: 62,
                crowdPickPercent: 6,
                signals: [{ type: "DRIFTING", label: "DRIFTING" }],
                sentiment: { positive: 32, negative: 42, neutral: 26 },
                stats: { speed: 76, stamina: "Medium", trend: "down" },
                aiInsight:
                    "Drifting in the market from 10/1 to 16/1. Connections might be saving for a later target. Best avoided today.",
                silkColor: "#5c5c1a",
                ...profile({
                    aiVerdict:
                        "Market drift is the key signal here. From 10/1 to 16/1 suggests connections are lukewarm. Mullins may be saving this horse for a later festival target. Avoid.",
                    pros: [
                        "Big price if circumstances fall right",
                        "Mullins yard always a threat",
                    ],
                    cons: [
                        "Clear market drift — 10/1 to 16/1",
                        "Connections likely targeting elsewhere",
                        "Inconsistent recent form",
                        "Only medium stamina for a 3m test",
                    ],
                    confidence: 28,
                    age: 8,
                    weight: "10st 12lb",
                    rating: 140,
                    trackRecord: { courseWins: 0, courseRuns: 2, distanceWins: 1, distanceRuns: 4, goingWins: 1, goingRuns: 3 },
                    recentRuns: [
                        { date: "2026-02-15", course: "Navan", position: "3rd", distance: "3m", going: "Soft", odds: "5/1" },
                        { date: "2026-01-04", course: "Leopardstown", position: "2nd", distance: "3m 1f", going: "Yielding", odds: "4/1" },
                        { date: "2025-12-01", course: "Fairyhouse", position: "1st", distance: "2m 4f", going: "Heavy", odds: "3/1" },
                    ],
                }),
            },
        ],
    },
    {
        id: "race-4",
        time: "15:30",
        name: "Boodles Cheltenham Gold Cup Chase",
        grade: "Grade 1",
        distance: "3m 2f",
        going: "Good to Soft",
        runners: 14,
        status: "upcoming",
        bankerPick: "Galopin Des Champs",
        valuePick: "Fastorslow",
        marketMover: "L'Homme Presse",
        punditPick: "Galopin Des Champs",
        topSignals: [
            { type: "BANKER", label: "Banker: Galopin Des Champs" },
            { type: "VALUE_BET", label: "Value: Fastorslow" },
            { type: "STEAMING", label: "Market Mover: L'Homme Presse" },
            { type: "PUNDIT_PICK", label: "Pundit: Galopin Des Champs" },
        ],
        horses: [
            {
                id: "h16",
                number: 1,
                name: "Galopin Des Champs",
                jockey: "P. Townend",
                trainer: "W.P. Mullins",
                form: "11-311",
                odds: "Evs",
                oddsDecimal: 2.0,
                aiRating: 96,
                crowdPickPercent: 42,
                signals: [
                    { type: "BANKER", label: "BANKER" },
                    { type: "PUNDIT_PICK", label: "PUNDIT PICK" },
                ],
                sentiment: { positive: 90, negative: 4, neutral: 6 },
                stats: { speed: 97, stamina: "Elite", trend: "up" },
                aiInsight:
                    "The Gold Cup king. Unbeaten at Cheltenham in his last three visits. Every metric favours this horse.",
                silkColor: "#2e5c1a",
                ...profile({
                    aiVerdict:
                        "The defining horse of this era. Three Cheltenham visits, three wins — a record that speaks for itself. Every single metric in our model gives this horse the highest score. The only debate is whether the price is too short, but the probability analysis supports even money. This is the banker of the meeting.",
                    pros: [
                        "Three from three at Cheltenham — unmatched",
                        "Highest AI rating in the entire festival (96)",
                        "Mullins/Townend — the best combination in racing",
                        "Elite stamina — loves the Gold Cup distance",
                        "90% positive social sentiment",
                    ],
                    cons: [
                        "Even money in the Gold Cup is always risky",
                        "That 3rd at Leopardstown in December",
                        "Target on his back — everyone wants to beat him",
                    ],
                    confidence: 92,
                    age: 9,
                    weight: "11st 10lb",
                    rating: 176,
                    trackRecord: { courseWins: 3, courseRuns: 3, distanceWins: 5, distanceRuns: 6, goingWins: 6, goingRuns: 7 },
                    recentRuns: [
                        { date: "2026-02-08", course: "Leopardstown", position: "1st", distance: "3m", going: "Yielding", odds: "4/6" },
                        { date: "2025-12-28", course: "Leopardstown", position: "3rd", distance: "3m", going: "Yielding to Soft", odds: "1/2" },
                        { date: "2025-11-17", course: "Punchestown", position: "1st", distance: "3m", going: "Soft", odds: "4/7" },
                    ],
                }),
            },
            {
                id: "h17",
                number: 2,
                name: "Fastorslow",
                jockey: "J.J. Slevin",
                trainer: "M.F. Morris",
                form: "22-112",
                odds: "5/1",
                oddsDecimal: 6.0,
                aiRating: 80,
                crowdPickPercent: 16,
                signals: [{ type: "VALUE_BET", label: "VALUE BET" }],
                sentiment: { positive: 63, negative: 17, neutral: 20 },
                stats: { speed: 88, stamina: "High", trend: "stable" },
                aiInsight:
                    "Our model suggests fair odds around 7/2. At 5/1, there's marginal value. A genuine each-way contender.",
                silkColor: "#1a3a5c",
                ...profile({
                    aiVerdict:
                        "A genuine Gold Cup contender at a reasonable price. Our model prices this at 7/2, so 5/1 offers value. Stays well, handles the ground, and runs consistently. The main danger to the favourite.",
                    pros: [
                        "Value at 5/1 — model says 7/2",
                        "Consistent performer — rarely runs badly",
                        "Handles all ground conditions",
                        "Main danger to the favourite",
                    ],
                    cons: [
                        "Two seconds suggest may lack the killer blow",
                        "Faces the best Cheltenham horse of this generation",
                        "Jockey less experienced at the highest level",
                    ],
                    confidence: 75,
                    age: 9,
                    weight: "11st 10lb",
                    rating: 170,
                    trackRecord: { courseWins: 0, courseRuns: 2, distanceWins: 3, distanceRuns: 5, goingWins: 4, goingRuns: 6 },
                    recentRuns: [
                        { date: "2026-02-08", course: "Leopardstown", position: "2nd", distance: "3m", going: "Yielding", odds: "3/1" },
                        { date: "2026-01-04", course: "Leopardstown", position: "1st", distance: "3m", going: "Yielding to Soft", odds: "2/1" },
                        { date: "2025-11-17", course: "Punchestown", position: "1st", distance: "3m", going: "Soft", odds: "5/2" },
                    ],
                }),
            },
            {
                id: "h18",
                number: 3,
                name: "L'Homme Presse",
                jockey: "C. Deutsch",
                trainer: "V. Williams",
                form: "11-211",
                odds: "8/1",
                oddsDecimal: 9.0,
                aiRating: 76,
                crowdPickPercent: 11,
                signals: [{ type: "STEAMING", label: "STEAMING" }],
                sentiment: { positive: 58, negative: 20, neutral: 22 },
                stats: { speed: 84, stamina: "High", trend: "up" },
                aiInsight:
                    "Significant market support. Odds shortened from 14/1 to 8/1 in the last 48 hours. Venetia Williams targeting this race specifically.",
                silkColor: "#5c1a3a",
                ...profile({
                    aiVerdict:
                        "The big market mover. From 14/1 to 8/1 in 48 hours signals genuine confidence from connections. Venetia Williams has targeted this race and her Cheltenham record is excellent. At 8/1, this represents the best value in the Gold Cup.",
                    pros: [
                        "Huge market mover — 14/1 to 8/1",
                        "Venetia Williams targeting Cheltenham",
                        "Won last two — form is strong",
                        "Good each-way value at 8/1",
                    ],
                    cons: [
                        "Untested at this level of competition",
                        "The move may have already been priced in",
                        "Cheltenham distance is new territory",
                    ],
                    confidence: 68,
                    age: 8,
                    weight: "11st 10lb",
                    rating: 164,
                    trackRecord: { courseWins: 1, courseRuns: 2, distanceWins: 2, distanceRuns: 3, goingWins: 3, goingRuns: 4 },
                    recentRuns: [
                        { date: "2026-02-01", course: "Sandown", position: "1st", distance: "3m", going: "Good to Soft", odds: "7/2" },
                        { date: "2026-01-01", course: "Kempton", position: "1st", distance: "3m", going: "Good", odds: "4/1" },
                        { date: "2025-11-23", course: "Ascot", position: "2nd", distance: "2m 5f", going: "Soft", odds: "5/1" },
                    ],
                }),
            },
            {
                id: "h19",
                number: 4,
                name: "Shishkin",
                jockey: "N. De Boinville",
                trainer: "N. Henderson",
                form: "11-342",
                odds: "10/1",
                oddsDecimal: 11.0,
                aiRating: 68,
                crowdPickPercent: 9,
                signals: [{ type: "OVERHYPED", label: "OVERHYPED" }],
                sentiment: { positive: 45, negative: 32, neutral: 23 },
                stats: { speed: 82, stamina: "Medium", trend: "down" },
                aiInsight:
                    "Name recognition inflating the price. Recent form doesn't justify single-figure odds. Vulnerable.",
                silkColor: "#5c3a1a",
                ...profile({
                    aiVerdict:
                        "A hero of the past trading on former glories. The crowd still loves Shishkin but the data screams caution. Three runs without a win, stamina only medium for a 3m2f test, and the market has him too short. Our model has a fair price of 20/1. Avoid.",
                    pros: [
                        "Top trainer/jockey combination",
                        "Class horse — proven Grade 1 winner",
                        "Crowd favourite — big atmosphere horse",
                    ],
                    cons: [
                        "Form figures (342) are declining",
                        "Stamina doubt over Gold Cup distance",
                        "10/1 is far too short — model says 20/1",
                        "Overhyped by name recognition",
                    ],
                    confidence: 35,
                    age: 10,
                    weight: "11st 10lb",
                    rating: 160,
                    trackRecord: { courseWins: 2, courseRuns: 4, distanceWins: 1, distanceRuns: 3, goingWins: 2, goingRuns: 5 },
                    recentRuns: [
                        { date: "2026-02-01", course: "Sandown", position: "2nd", distance: "3m", going: "Good to Soft", odds: "5/2" },
                        { date: "2026-01-01", course: "Kempton", position: "4th", distance: "3m", going: "Good", odds: "2/1" },
                        { date: "2025-11-23", course: "Ascot", position: "3rd", distance: "2m 5f", going: "Soft", odds: "7/4" },
                    ],
                }),
            },
            {
                id: "h20",
                number: 5,
                name: "Bravemansgame",
                jockey: "H. Cobden",
                trainer: "P. Nicholls",
                form: "12-121",
                odds: "12/1",
                oddsDecimal: 13.0,
                aiRating: 72,
                crowdPickPercent: 8,
                signals: [{ type: "SOCIAL_BUZZ", label: "SOCIAL BUZZ", detail: "420+ mentions" }],
                sentiment: { positive: 56, negative: 22, neutral: 22 },
                stats: { speed: 81, stamina: "Elite", trend: "stable" },
                aiInsight:
                    "Social media is buzzing. Paul Nicholls is due a big-race winner. The stamina is there for this trip.",
                silkColor: "#1a5c5c",
                ...profile({
                    aiVerdict:
                        "Social buzz is the key signal here — 420+ mentions and climbing. Paul Nicholls has been quiet at this festival and he's due a big result. Elite stamina makes this a legitimate threat over the Gold Cup distance. At 12/1, there's sneaky each-way value.",
                    pros: [
                        "420+ social mentions — trending",
                        "Elite stamina — perfect for 3m2f",
                        "Paul Nicholls due a festival winner",
                        "Good each-way value at 12/1",
                    ],
                    cons: [
                        "Two seconds suggest bridesmaid potential",
                        "Needs everything to fall right to beat favourite",
                        "Social buzz alone doesn't win races",
                    ],
                    confidence: 58,
                    age: 9,
                    weight: "11st 10lb",
                    rating: 162,
                    trackRecord: { courseWins: 1, courseRuns: 3, distanceWins: 3, distanceRuns: 4, goingWins: 2, goingRuns: 4 },
                    recentRuns: [
                        { date: "2026-02-01", course: "Sandown", position: "1st", distance: "3m", going: "Good to Soft", odds: "5/1" },
                        { date: "2026-01-01", course: "Kempton", position: "2nd", distance: "3m", going: "Good", odds: "7/2" },
                        { date: "2025-11-23", course: "Ascot", position: "1st", distance: "3m 1f", going: "Soft", odds: "4/1" },
                    ],
                }),
            },
        ],
    },
];

export const schedule: DaySchedule[] = [
    { label: "Today", date: "2026-03-10", races: cheltenhamDay1 },
    { label: "Tomorrow", date: "2026-03-11", races: [] },
    { label: "Wednesday", date: "2026-03-12", races: [] },
    { label: "Thursday", date: "2026-03-13", races: [] },
];

export function getRaceById(id: string): Race | undefined {
    return cheltenhamDay1.find((r) => r.id === id);
}

export function getHorseById(horseId: string): { horse: Horse; race: Race } | undefined {
    for (const race of cheltenhamDay1) {
        const horse = race.horses.find((h) => h.id === horseId);
        if (horse) return { horse, race };
    }
    return undefined;
}
